version: "3.9"

services:
  finance_manager:
    container_name: finance_manager
    build: .
    working_dir: /server
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    restart: on-failure
